server:
  port: 8083

spring:
  config:
    import: optional:configserver:http://localhost:8085
  datasource:
    url: jdbc:mysql://localhost:3306/microservices_3
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  application:
    name: RATING-SERVICE

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
